

all: 2 3 4 5 6 8 9 10 11 12 13 14 15 16 
	make transfert

1:
	sed 's/é/\\351/g' temps1 > temps1iso
	gnuplot temps1iso

2: 
	sed 's/é/\\351/g' temps2 > temps2iso
	gnuplot temps2iso
3:
	sed 's/é/\\351/g' temps3 > temps3iso
	gnuplot temps3iso
4:
	sed 's/é/\\351/g' temps4 > temps4iso
	gnuplot temps4iso
5:
	sed 's/é/\\351/g' temps5 > temps5iso
	gnuplot temps5iso
6:
	sed 's/é/\\351/g' temps6 > temps6iso
	gnuplot temps6iso
7:
	sed 's/é/\\351/g' temps7 > temps7iso
	gnuplot temps7iso
8:
	sed 's/é/\\351/g' temps8 > temps8iso
	gnuplot temps8iso
9:
	sed 's/é/\\351/g' temps9 > temps9iso
	gnuplot temps9iso
10:
	sed 's/é/\\351/g' temps10 > temps10iso
	gnuplot temps10iso
11:
	sed 's/é/\\351/g' temps11 > temps11iso
	gnuplot temps11iso

12:
	sed 's/é/\\351/g' temps12 > temps12iso
	gnuplot temps12iso

13:
	sed 's/é/\\351/g' temps13 > temps13iso
	gnuplot temps13iso




14:
	sed 's/é/\\351/g' temps14 > temps14iso
	gnuplot temps14iso


15:
	sed 's/é/\\351/g' temps15 > temps15iso
	gnuplot temps15iso

16:
	sed 's/é/\\351/g' temps16 > temps16iso
	gnuplot temps16iso

17:
	sed 's/é/\\351/g' temps17 > temps17iso
	gnuplot temps17iso




# pour changer la taille 
# sed 's/size 700,620/size 700,520/' -i temps*

transfert:
	cp temps*.png ./../../figures/